// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjiRklJIjRgpIs92dy_R6SnM2CrxN9tNY',
    appId: '1:683303746359:web:2465b7268538e14c9cf8b2',
    messagingSenderId: '683303746359',
    projectId: 'lush-layer',
    authDomain: 'lush-layer.firebaseapp.com',
    storageBucket: 'lush-layer.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArAWO_TSFpOg19kpM_iCvUZnuFMXljB7Y',
    appId: '1:683303746359:android:309859f6e8dfcba69cf8b2',
    messagingSenderId: '683303746359',
    projectId: 'lush-layer',
    storageBucket: 'lush-layer.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjiRklJIjRgpIs92dy_R6SnM2CrxN9tNY',
    appId: '1:683303746359:web:ecb078f70af4ee029cf8b2',
    messagingSenderId: '683303746359',
    projectId: 'lush-layer',
    authDomain: 'lush-layer.firebaseapp.com',
    storageBucket: 'lush-layer.appspot.com',
  );

}